### ISSUE TITLE
"Drag" is broken.

### ISSUE THREAD

**Issue by Vordai-of-Prophecy** [prophecymud/go-prophecy-issues#102]
Nothing happens when attempting to drag a mob. That is, no message received either way ("You can't drag that!" vs "You drag a fisherman north") and the targeted mob is unaffected.

**Comment by anhegofcherek** [comment]
Thanks - unfortunate combo of things there - a bug I introduced that accidentally tries to use the name as direction (so comparing "fisherman" to n/e/s/w), combined with a long-standing design issue where if it can't match the direction, it fails silently!

I've fixed the bug, I'll address the UX issue later, thanks!
