### ISSUE TITLE
EmNotes last note not staying read

### ISSUE THREAD

**Issue by Ranfir** [prophecymud/go-prophecy-issues#103]
The last emnote always appears as unread when I log in.

**Comment by anhegofcherek** [comment]
Interesting - I'm not seeing this! Is anyone else...?

**Comment by Ranfir** [comment]
I definitely reproduced this on 2 different chars, but I'm not seeing it now.

**Comment by Ranfir** [comment]
And... it seems to be happening again with the current emnote.

**Comment by Ranfir** [comment]
```
Eirela oocs 'when I did "emnote catchup" it appears to stop the last one persisting as unread'
```

**Comment by Ranfir** [comment]
Also applies to the most recent qnote for me now.

**Comment by Ranfir** [comment]
And the most recent news and change as well.

**Comment by kerowa** [comment]
Happening to me too -- my most recent news, story and emnotes were ones I know for certain I read already

**Comment by anhegofcherek** [comment]
Right, I think that was an issue with GoProph using nanoseconds for time precision, but saving/loading everything in seconds to keep compatibility with CProph - hopefully I've fixed it for now by truncating all times to seconds in the checks...

**Comment by anhegofcherek** [comment]
As far as I can tell, I was correct and this is now fixed - please re-open if you see otherwise though!
