### ISSUE TITLE
push/drag defaults to north when no direction is specified

### ISSUE THREAD

**Issue by Ranfir** [prophecymud/go-prophecy-issues#109]
```
pu dog
You slam into a little dog with all your weight! OW!

[3405/3405 978/978 680/688 154|I  ] (NS) < > 
( )
scan
Looking around you see:
A little dog, nearby to the north.
The city guard, nearby to the north.
The city guard, nearby to the north.
```

**Comment by anhegofcherek** [comment]
Thanks

CProph used to just error silently if you did that, I'd argue my port is better ;)

I've just improved it now though so you should get a helpful error message if you don't supply a direction, or if you supply an invalid direction - thanks!
