### ISSUE TITLE
oocbuffer uses CES Timezone

### ISSUE THREAD

**Issue by grekan** [prophecymud/go-prophecy-issues#112]
![image](https://user-images.githubusercontent.com/30678526/72311479-cf381a00-3652-11ea-8cb3-524a34f7328e.png)

Timezone is ahead of system by an hour. 

Could we possibly just change the server OS time to UTC permanently? I assume the mud is checking time against the OS.

**Comment by anhegofcherek** [comment]
Should be fixed on next reboot, thanks!

I'd sort server time if I easily could...!
