### ISSUE TITLE
Aq gain crashes mud?

### ISSUE THREAD

**Issue by kerowa** [prophecymud/go-prophecy-issues#114]
![2020-01-14](https://user-images.githubusercontent.com/59801202/72359837-4057eb80-36ac-11ea-836b-e66789e399ad.png)

Did I break the mud :(

**Comment by anhegofcherek** [comment]
You did - thank you!

**Comment by anhegofcherek** [comment]
Silly typo that I'm surprised the linters didn't catch - fixed on next deploy, thanks!
