### ISSUE TITLE
Having negative mana causes a crash

### ISSUE THREAD

**Issue by Ranfir** [prophecymud/go-prophecy-issues#117]
Tharec ended up with negative mana after catching the plague.
Attempting to log in as him now apparently crashes the mud.

**Comment by Ranfir** [comment]
Just to be clear, it sounds like there are 2 potentially separate bugs here:
1. Moving with negative mana: I had negative mana for a number of ticks before defeating the mob. The MUD didn't crash until I attempted to move south.
2. Logging in with the plague effect.

**Comment by anhegofcherek** [comment]
Thanks!

I don't believe this has anything to do with negative mana - looks like you managed to find two (related!) issues - affect data wasn't properly being handled for web (1) or plague (2) - should be fixed on next deploy now, thanks!
