### ISSUE TITLE
Items sold to a merchant change total quantity - Infinite items

### ISSUE THREAD

**Issue by grekan** [prophecymud/go-prophecy-issues#124]
Clan potion seller was sold an amount of rusty yellow potions:

![image](https://user-images.githubusercontent.com/30678526/72672497-f020b680-3a28-11ea-86c8-f1dde33afb6c.png)

This made every item equal that item in quantity. 

Then I bought one:

![image](https://user-images.githubusercontent.com/30678526/72672499-f747c480-3a28-11ea-9739-4c2f8786860b.png)

And it went down. 

Here's an example with more than one potion:

![image](https://user-images.githubusercontent.com/30678526/72672504-12b2cf80-3a29-11ea-9e72-949cecde991e.png)

This seems like it would apply to any merchant with infinite items.

**Comment by grekan** [comment]
I forgot to mention once all sold potions were removed, items returned to normal 0 and were still able to be purchased.

**Comment by Ranfir** [comment]
My rough recollection is that CProph behaved like this as well.

**Comment by grekan** [comment]
Certainly the behaviour carries on outside clan potion seller:

![image](https://user-images.githubusercontent.com/30678526/72672825-a8049280-3a2e-11ea-8269-df86e4640f95.png)

**Comment by anhegofcherek** [comment]
Thanks!

Took me a moment to realise this was purely a display bug - "it went down" was re the number, not the bug!

I've fixed the issue (of the count being reused) as well as enhancing `list` to display `*` as quantity of `INVENTORY` (i.e. infinite) items sold - cheers
