### ISSUE TITLE
Emily quests now running at intervals of 10-12 days

### ISSUE THREAD

**Issue by Vordai-of-Prophecy** [prophecymud/go-prophecy-issues#125]
Notes:
Emily FTI quests were running approximately every two hours on Sunday afternoon? 1/20
As of Sunday evening, the Emily quest schedules indicate that the quests will run 10-12 days apart.

**Comment by anhegofcherek** [comment]
Ah yes - actually it's the opposite problem, she was running them too frequently! Thus I punted them a few days out until I fix things

**Comment by anhegofcherek** [comment]
She should be back to normal now - I'd introduced a bug while porting that meant the fixed interval part of her scheduling was ignored!
