### ISSUE TITLE
dash doesn't work against some mobs

### ISSUE THREAD

**Issue by Ranfir** [prophecymud/go-prophecy-issues#130]
This was an issue in CProph as well:
```
You dash into the room!
You're facing the wrong end.
ZZchulk is in excellent condition. 
```

**Comment by anhegofcherek** [comment]
This specific instance is because ZZchulk has a `GRALL` mprog to attack everyone entering - I believe it's _specifically_ to make it harder for bsers...

Do you have other examples, or is this likely to generally be the case?

**Comment by Ranfir** [comment]
Got it. IMO, builders shouldn't do that unless there's a very good reason to do so.

**Comment by anhegofcherek** [comment]
Agreed!
