### ISSUE TITLE
Clan Title is missing space

### ISSUE THREAD

**Issue by grekan** [prophecymud/go-prophecy-issues#136]
**clan title Tze Test**
Title changed.

**clan who**
[ 91 Send Sor ]    ( 1) TzetielTest
[ 72 Riva Pri ]    ( 2) Krondig is Grekan.

I couldn't avoid the title sucking into Tzetiel's name. I have to put `` ahead of the title to generate the space.

**Comment by anhegofcherek** [comment]
Fixed in next deploy, thanks - hadn't ported that behaviour!
