### ISSUE TITLE
Astring Appears to be Broken?

### ISSUE THREAD

**Issue by grekan** [prophecymud/go-prophecy-issues#137]
Was trying to restring a piece of eq and it kept rejecting it

**astring light "*Ag* *vVv* aquest light torch magical flames" "`8|`&*`8|`2v`@V`2v`8|`&*`8| `7A `#T`&o`3rch `7of `^M`&a`6g`&i`6c`&a`6l `!F`1l`&a`1m`&e`1s``" "`8|`&*`8|`2v`@V`2v`8|`&*`8| `7A `#T`&o`3rch `7of `^M`&a`6g`&i`6c`&a`6l `!F`1l`&a`1m`&e`1s``"
You can't make quest points!!!**

_You can't make quest points!!!_

![image](https://user-images.githubusercontent.com/30678526/73148287-8e47f880-4089-11ea-863b-e86789add4df.png)

**Comment by anhegofcherek** [comment]
Should be the same behaviour as in CProph - can't use "quest" in the name at all!
