### ISSUE TITLE
MUD crashed after attempting to sell an item to merchants in Sendar

### ISSUE THREAD

**Issue by Vordai-of-Prophecy** [prophecymud/go-prophecy-issues#140]
Notes:
Entered the following command: "sell polar"
Crashed when attempting to sell to Saxan (apprentice weaponsmith) and again with Maitland (armorer) in Sendar.

**Comment by anhegofcherek** [comment]
Fixed, thanks - was reworking how people-in-a-room is stored, and didn't quite update the code to look for a shopkeeper properly
