### ISSUE TITLE
Mud crashed after I typed "list" to check what I could buy from a merchant......

### ISSUE THREAD

**Issue by kerowa** [prophecymud/go-prophecy-issues#141]

**Comment by kerowa** [comment]
Tested on a second merchant -- definitely buggy.  Crashed mud second time.

**Comment by kerowa** [comment]
NOTE - Mud also crashes if you try to BUY items from a merchant.

**Comment by anhegofcherek** [comment]
Fixed, thanks - was reworking how people-in-a-room is stored, and didn't quite update the code to look for a shopkeeper properly
