### ISSUE TITLE
Camaar jailor mprog broken

### ISSUE THREAD

**Issue by Ranfir** [prophecymud/go-prophecy-issues#144]
Haven't checked if this was actually fixed or not. Opening an issue just in case it was forgotten.

**Comment by anhegofcherek** [comment]
Hah, thank you - it is indeed fixed...

...entirely accidentally, by me fixing #151 

(The jailor also uses `$q`, just in a way where the failure mode was silent rather than crashy, so it was much less obvious)

Thanks :)
