### ISSUE TITLE
Item stacks resetting to 1

### ISSUE THREAD

**Issue by Eralak** [prophecymud/go-prophecy-issues#146]
I've noticed on two separate occasions, that certain stacks of items are being reset to 1 inside bags. It happens sometimes when logging out and back in, will do further testing to get more specifics.

Bag: an Enormous Cooking Pot
Items being reset: a scroll of recall, a slimy green potion

**Comment by anhegofcherek** [comment]
Did you perhaps die? Scrolls and potions rot (slowly) after death

**Comment by anhegofcherek** [comment]
From a glance at the amount of times you've died recently, I suspect that was it - if you believe otherwise, please reopen this!
