### ISSUE TITLE
Players quitting the game seems to disconnect all other players. 

### ISSUE THREAD

**Issue by grekan** [prophecymud/go-prophecy-issues#15]
Qethia has left the game.

|3582/3582|1002/1002|655/655|931 4826|0:00|The Temple of UL|(NSU)[ ]
#Connection lost.

...

Qethia and I tested this a fair amount, and it impacted both of us. There was one exception when I logged off Grekan and logged back in, she didn't get impacted, but all other times we were able to reproduce.

**Comment by grekan** [comment]
In a related piece. I spammed myself to a disconnection and Qethia got disconnected as well.

**Comment by grekan** [comment]
The whole time I was in Char creation Qethia couldn't log in.

**Comment by anhegofcherek** [comment]
I think this should now be fixed - I certainly can't reproduce it; please reopen if you can!
