### ISSUE TITLE
Bless potion doesn't bless while fighting - gives message indicating already blessed. 

### ISSUE THREAD

**Issue by grekan** [prophecymud/go-prophecy-issues#153]
So I was fighting a mob and it kept saying I had sanc, but aff was not showing it. 
![image](https://user-images.githubusercontent.com/30678526/74690999-0c8e4b00-51af-11ea-8b9a-dbcb9ca8fb1d.png)

I fled and quaffed and then it worked. 
![image](https://user-images.githubusercontent.com/30678526/74691005-1617b300-51af-11ea-8982-6625a7543a64.png)

2 issues:
Bless not happening from pot due to fighting. 
It erroring and showing the wrong message.

**Comment by anhegofcherek** [comment]
> So I was fighting a mob and it kept saying I had sanc, but aff was not showing it.

I assume you mean bless, not sanc?

**Comment by anhegofcherek** [comment]
I'm not sure I understand how there are two issues

I see one, which predates GoProphecy - if you try to bless someone fighting, you get the "already blessed" message rather than a fighting-specific message (fixed in next deploy) - what's the other issue you see?

**Comment by grekan** [comment]
Yes I meant bless. 

There's only 2 issues if you're meant to be able to quaff a potion with bless and feel the affects during combat, which is what I assumed. Sanc and the various armor spells in potions work during combat as far as I know. 

If bless is not meant to take affect during combat and the message has been changed then the issue is resolved.

**Comment by anhegofcherek** [comment]
> If bless is not meant to take affect during combat

So it seems:

```
    if ( victim->position == POS_FIGHTING || is_affected( victim, sn ) ) {
        if (victim == ch)
            send_to_char("You are already blessed.\n\r",ch);
        else 
            act("$N already has divine favor.",ch,NULL,victim,TO_CHAR);
        return;
    }    
```
