### ISSUE TITLE
Connectivity

### ISSUE THREAD

**Issue by grekan** [prophecymud/go-prophecy-issues#159]
I keep getting disconnected and having other issues. 

The mud is now consistently dropping every 6th packet or so for me:

![image](https://user-images.githubusercontent.com/30678526/75098327-a1fc5700-5582-11ea-8a3e-1ef3ff0d8329.png)

At the same time I run a ping to google, so it's not my internet. 

![image](https://user-images.githubusercontent.com/30678526/75098329-acb6ec00-5582-11ea-9fe7-7da4bd26011f.png)

![image](https://user-images.githubusercontent.com/30678526/75098332-b2143680-5582-11ea-9e20-e2f1207e23c2.png)

A MTR is showing the packet loss is likely starting at the mud:

![image](https://user-images.githubusercontent.com/30678526/75098337-cce6ab00-5582-11ea-8f94-3facb57d9547.png)

(The packet loss on the MTR is not consistent all the way through so the packet loss before the mud hops are not real values - however, we confirmed the mud drops are roughly 18% so we take that value as real). 

Not sure what is causing the issue. I've had other outages in the last couple of weeks where I get d/c for about 10 minutes. Mud unpingable then also.

**Comment by grekan** [comment]
As of right now issue is subsiding. So about 14:20 EST to 15:03 EST today.

**Comment by grekan** [comment]
Time of Incident: 9:55 EST / 02:55 UTC

Eirela was killing mountain gorilla and I was watching, using say. 

Mud became unresponsive.

Mud became responsive again 3 minutes later at 9:58 EST / 02:55 UTC

We all went Linkdead

The Medical Facility
  Fashioned from an opened corner of the compound and a few walls, the
medical facility is a testament to cleanliness and order.  Nothing is out of
place, and amazingly, everything is in its place.  The floor has been
finished with white marble tiles, and is so clean one could eat off of it. 
Along the walls, storage has been erected for the doctor's various
instruments and medicinal substances.  In here is where one could expect to
find exactly the help that one needs.  

[Exits: north west up]
     A few beds, draped in white linens, sit along the far wall.
     A ceramic fountain stands in the middle of the room.
(Linkdead) Lord Dhreneval is resting on a white linen bed.
The doctor patiently waits to assist you.

Mud didn't crash either. 

Pings confirm internet connecitvity, but no response from the mud. 

Ping to google.com
Ping statistics for 172.217.0.238:
    Packets: Sent = 287, Received = 287, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 12ms, Maximum = 38ms, Average = 18ms

Ping to mud.prophecy.lu
Ping statistics for 213.166.63.242:
    Packets: Sent = 186, Received = 154, Lost = 32 (17% loss),
Approximate round trip times in milli-seconds:
    Minimum = 119ms, Maximum = 142ms, Average = 124ms

**Comment by anhegofcherek** [comment]
This sounds like a transient networking thing without identifiable cause and that could easily be not-Prophecy so I intend to close this, unless you've objections / alternate suggestions?
