### ISSUE TITLE
finger is laggy

### ISSUE THREAD

**Issue by Ranfir** [prophecymud/go-prophecy-issues#160]
e.g. `finger drosta` takes between 2s and 11s.

**Comment by anhegofcherek** [comment]
Yep; it used to have a partial copy of the pfile loading code, hacked to only load the relevant data -I made it load the whole pfile which is cleaner and safer, but interacts poorly with some of the performance hits from the object-loading rewrite...

**Comment by anhegofcherek** [comment]
I'm afraid I don't have an exact reference to hand but with my changes to the datastructures for objects (TL;DR now a set not a list) that massively increased performance, this should now be fine!
