### ISSUE TITLE
Brew exploded my keyring

### ISSUE THREAD

**Issue by grekan** [prophecymud/go-prophecy-issues#166]
brew sanc
a Rivan keyring cannot contain any more spells.

brew sanc
a Rivan keyring explodes violently!
Your acid blast -=- EVISCERATES -=- you!

![image](https://user-images.githubusercontent.com/30678526/77272545-e402e080-6c87-11ea-9076-5698cf29a8c6.png)

Why on earth would it try and brew into the keyring?

Put all my bags down and just had vials in my inventory and my WWP exploded next:

rew sanc
Emblem of Brotherhood explodes violently!
Your acid blast -<* CLEAVES *>- you!
You feel yourself slow down.

![image](https://user-images.githubusercontent.com/30678526/77272684-25938b80-6c88-11ea-8057-e5664070abf9.png)

**Comment by grekan** [comment]
Realized I should have been holding the vial, but I'm unwilling to try at this point, given other eq is exploding.

**Comment by anhegofcherek** [comment]
Nicely found, thank you! Rather niche bug that was the interesting intersection of a number of factors. Fixed on next reboot!

**Comment by grekan** [comment]
Probably a different issue, but brew still doesn't work. 

You hold An empty vial in your hand.

|2052/2042|2001/1991|653/653|528 2|0:00|Grekan's Office|(e)[ ]
brew sanc
An empty vial cannot contain any more spells.

|2052/2042|2001/1991|653/653|528 2|0:00|Grekan's Office|(e)[ ]
ident vial
You do not have an item called vial.

|2052/2042|2001/1991|653/653|528 2|0:00|Grekan's Office|(e)[ ]
rem vial
You stop using An empty vial.

|2052/2042|2001/1991|653/653|528 2|0:00|Grekan's Office|(e)[ ]
ident vial
You identify An empty vial:

Object 'vial' is type potion.
Extra flags: none.
Weight is 1, value is 400, wear level is 15.
Wear location is hold.
Level 45 spells of: 'reserved' 'reserved' 'reserved' 'reserved'.

![image](https://user-images.githubusercontent.com/30678526/77490555-87333180-6e11-11ea-9a6e-e6161573c40b.png)
