### ISSUE TITLE
Brew will not fill empty vial

### ISSUE THREAD

**Issue by grekan** [prophecymud/go-prophecy-issues#167]
brew sanc
An empty vial cannot contain any more spells.

rem vial
You stop using An empty vial.

ident vial
You identify An empty vial:

Object 'vial' is type potion.
Extra flags: none.
Weight is 1, value is 400, wear level is 15.
Wear location is hold.
Level 45 spells of: 'reserved' 'reserved' 'reserved' 'reserved'.

Brew doesn't seem to understand reserved is not a spell.

**Comment by anhegofcherek** [comment]
More like `skill_lookup` doesn't understand that `""` isn't a spell - fixed and live now, thanks

**Comment by grekan** [comment]
Thank you Anheg!
