### ISSUE TITLE
Poisoner's Hideaway

### ISSUE THREAD

**Issue by grekan** [prophecymud/go-prophecy-issues#168]
Apparently Slaver's Cove is race/class limited to nyissan's only.

**Comment by grekan** [comment]
Being invis bypasses the mprog, may not be a real issue.

**Comment by anhegofcherek** [comment]
Poisoner's Hideaway you mean?

**Comment by grekan** [comment]
Yes that is what I meant. Subject changed.

**Comment by anhegofcherek** [comment]
Thanks for raising this, but this isn't a GoProphecy issue - it's intended behaviour of the area - with the invis workaround ensuring the area isn't _actually_ fully race-restricted
