### ISSUE TITLE
Dash not working

### ISSUE THREAD

**Issue by grekan** [prophecymud/go-prophecy-issues#169]
Syntax: dash <direction> <command>

|3592/3592|1002/1002|655/655|18 59|0:00|The Medical Facility|(nwu)[ ]
dash west fart

|3592/3592|1002/1002|655/655|18 59|0:00|The Medical Facility|(nwu)[ ]

Tried with various directions and commands, doesn't seem to be working Aisyl advised it to me first, she also can't get it working with bs or kill.

**Comment by anhegofcherek** [comment]
Missed this when porting; fixed now, thanks!
