### ISSUE TITLE
Issues during char creation...

### ISSUE THREAD

**Issue by grekan** [prophecymud/go-prophecy-issues#17]
Was trying to select home city of Sendar but inputting "sendar" it wouldn't accept it. Appears to be case sensitive.

During char creation there is a "skill" called "Reserved" which is 99cp. 

During char creation all inputs while working, also get "No help on that word." added on. 

![image](https://user-images.githubusercontent.com/30678526/68087736-664c4e80-fe26-11e9-8bb0-320c5cf5a24b.png)

**Comment by anhegofcherek** [comment]
Thanks. In future, could you file an issue per issue please? Makes my interactions (tracking, seeing what's up at a glance etc.) much easier

**Comment by anhegofcherek** [comment]
> Was trying to select home city of Sendar but inputting "sendar" it wouldn't accept it. Appears to be case sensitive.

Fixed

**Comment by anhegofcherek** [comment]
This should all now be fixed apart from #19, thanks!
