### ISSUE TITLE
Pushing a mob into an adjoining room changed case settings on the mob's string.

### ISSUE THREAD

**Issue by Qethia** [prophecymud/go-prophecy-issues#2]
Originally: A little dog is trying to find a place to pee.
After pushing west: A lITtLe dOg Is Resting Here.
Note: mob string started out originally in plain text, but it's using a formatted string in the 'after' scenario - color, bold, etc., not sure what the term is for that...

**Comment by anhegofcherek** [comment]
Fixed, thank you! I messed up many nuances of porting string capitalisation...
