### ISSUE TITLE
Crash caused missing EQ

### ISSUE THREAD

**Issue by taltig** [prophecymud/go-prophecy-issues#21]
The first couple crashes today just reset us back to where we were

I casted nexus on Amagar out of Mal Yaska, quit, mud crashed, rejoined as Ufsss, Nexus was gone since the crash, but also lost a Grul's Club, Beaten Vest, Diamond Bracer, Pendant of Belar, and a couple other things I'm guessing.. Nothing I'm worried about, but it didn't go back to my inventory or his.

**Comment by anhegofcherek** [comment]
Were they items you'd recently picked up, or with any other significance?

If the former, that's a known issue - your character will revert to their most recent save

Thanks!

**Comment by anhegofcherek** [comment]
(If you'd like me to roll you back/forwards or similar while testing, just let me know)
