### ISSUE TITLE
Sendar Grocer

### ISSUE THREAD

**Issue by dhreneval** [prophecymud/go-prophecy-issues#22]
Today I was greeted by our local friendly Sendar Grocer of Sendar's General Store. It stuck me as quite odd, however, as they had greeted me thus:

> 20191105-13:25:12-3036 The grocer says 'Welcome to the General Store, the grocer.'

I think mayhap their variables are confused.

**Comment by anhegofcherek** [comment]
Fixed, thanks! Had some checks backwards when parsing these for mprogs
