### ISSUE TITLE
Creation issue: Unable to resume creation of a char after intentionally disconnecting partway through creation process.

### ISSUE THREAD

**Issue by Qethia** [prophecymud/go-prophecy-issues#24]
Began creation of a new character, 'Blowie'.

Midway through, d/c'd intentionally

Reconnected and attempted to add 'Blowie' again as new char name. Was disconnected with the following msg:

By what name do you wish to be known? Name:Blowie
--- Disconnected on Thursday, November 07, 2019, 10:45 AM ---
--- Connected for 0 days, 0 hours, 0 minutes, 3 seconds. ---

--- Received 33 lines, sent 2 lines.
--- Output buffer has 3109/5000 lines in it (62.2% full).
--- Matched 0 triggers, 0 aliases, and 1 timer fired.
The "GoProph" server has closed the connection

This does not happen on CProph. That lets me d/c during creation and then start all over with no issues.

Note: On one subsequent attempt, it did give this:
By what name do you wish to be known? Blowie
That character is already playing.
Do you wish to connect anyway (Y/N)?

**Comment by anhegofcherek** [comment]
Thanks! Looks like I didn't port over the disconnection-detection...

**Comment by anhegofcherek** [comment]
This should now be fixed, thanks!
