### ISSUE TITLE
Varon Contradiction

### ISSUE THREAD

**Issue by dhreneval** [prophecymud/go-prophecy-issues#30]
It looks like Varon will let you in to KoP clanhall even though he says you can't enter right now.

> Varon says 'You can't enter at the moment.'
> Varon steps aside and lets you pass.

Not sure if this is temporarily intended behavior or not - I certainly appreciate it as things are right now!

**Comment by anhegofcherek** [comment]
Thanks - you've definitely found a bug, but it's not obvious to me where exactly it is!

If you find any examples of similar behaviour, they'd help narrow it down please

**Comment by anhegofcherek** [comment]
Got it, thanks! Missed case-insensitivity when porting mprog parsing, so `IF` wasn't getting treated as an mprog if-statement, instead just as a regular game command
