### ISSUE TITLE
PUT A LID ON IT!!!

### ISSUE THREAD

**Issue by dhreneval** [prophecymud/go-prophecy-issues#31]
While fighting A Giant Tentacled Monster the other day, I noticed that after sending 12 cast 'ray of truth' commands (possibly more than once,) I had received, during combat, the following messages:

> *** PUT A LID ON IT!!! ***
> No way! You are fighting.

It looks like I was able to produce this series of messages in this circumstance at least twice.

**Comment by anhegofcherek** [comment]
As far as I can tell, that's exactly the same as the CProph behaviour - what was your expectation / what difference did you see?
