### ISSUE TITLE
Unable to put in stash

### ISSUE THREAD

**Issue by dhreneval** [prophecymud/go-prophecy-issues#32]
After discovering that stash is a thing, I attempted to use it on GoProph on account of being unclanned. The result was that I was unable to put my [Rivan] A Round Shield in stash.

> put rivan stash
> I see no stash here.

Meanwhile, inv reports the following:

> You are carrying:
>      [Rivan] A Round Shield

**Comment by anhegofcherek** [comment]
Thanks! That's correct (if not a very clear message) - you can currently only put in / take from your stash if you're clanned and in your locker room - I think I intended it to be purely an alternative to lockers at first!

It's also supposed to be disabled, which I accidentally missed when porting over from CProph - I'll rectify that!

**Comment by anhegofcherek** [comment]
Re-disabled, thanks
