### ISSUE TITLE
Scrimmage! But, wait.

### ISSUE THREAD

**Issue by dhreneval** [prophecymud/go-prophecy-issues#33]
After Qethia and I had joined in a scrimmage and readied ourself for bloody combat to the death, we have discovered that we can not, in fact, initiate combat actions against other players involved in the scrimmage. Attempts by either of us to do harm unto the other were met with a message informing us that we must go pk if we want to do these things.

> k qethia
> You must go pk if you want to kill players.

**Comment by anhegofcherek** [comment]
Can't reproduce this - do you have any more context please?

**Comment by anhegofcherek** [comment]
From talking to @Qethia it sounded like the scrimmage never launched, which would make this expected behaviour (not the not-launching, but the inability to fight) - do you recall it launching / have any logs please?
