### ISSUE TITLE
Scrimmage! But wait (Episode Two)

### ISSUE THREAD

**Issue by dhreneval** [prophecymud/go-prophecy-issues#34]
It would appear that two people joining an Emily scrimmage, then leaving, will leave Emily in an indefinite state of scrimmage until server reset. The scrimmage appears endless and blocks further interaction with Emily, such as cashing in Emily eggs. It is currently unknown whether scheduled Emily events will interrupt this behavior.

**Comment by dhreneval** [comment]
Also, as we were unable to do harm to one another in the scrimmage, it is currently unknown if winning the scrimmage could complete the scrimmage and return Prophecy to business as usual.

**Comment by anhegofcherek** [comment]
I couldn't reproduce this - Emily aborted the scrimmage after two people left, because of insufficient participants. Tell me more, please?
