### ISSUE TITLE
Notes are broken

### ISSUE THREAD

**Issue by prophnoran** [prophecymud/go-prophecy-issues#39]
Qethia sent me a note -- I never saw it. She sees 3 notes in `note list`, two of which are to me; I see just one in `note list`, which is one I wrote to all.

I wrote a note to all; when I ran `note post`, I got

`NOTE: you have a new notes`

spammed to me, like, several screenfulls.

There's an off-by-one error in note indexing:

#!prompt [3441/3441H] [2021/2021M] [656/656V] NS>
 note list
[  0 ]From:      Noran To:            all Subject: test test
#!prompt [3441/3441H] [2021/2021M] [656/656V] NS>
 note read 0
There aren't that many notes.

#!prompt [3441/3441H] [2021/2021M] [656/656V] NS>
 note read 1
[  0]
From:      Noran
 Subject: test test
 Date: 2019-11-21T01:48:19+01:00

**Comment by anhegofcherek** [comment]
Should all be fixed now, thanks
