### ISSUE TITLE
Notes Remain Unread Between Logins

### ISSUE THREAD

**Issue by grekan** [prophecymud/go-prophecy-issues#45]
Logged in, read the only note I had (about clan bank balance). 

Logged out. 

Logged in, saw the same note as unread again. 

Intentionally logged out and back in. 

Note was unread again. 

The notes remain read only so long as I'm logged in. 

Tried with Emnote as I had 5 of them. Only 1 remains unread upon login. 

Posted a note, did unread, bank note was back to being unread. 

Logged out and back in. 

Unread note was the bank note (note 0 of 1), my test note (note 1) remained read. 

Emnote 4 remained unread, but 0-3 were read. 

I saved between each login and logout.

**Comment by anhegofcherek** [comment]
If I read this correctly, it's only _the most recent_ note (or equivalent), in which case that should be fixed now, thanks!
