### ISSUE TITLE
Stat / Max Colour Bleed

### ISSUE THREAD

**Issue by grekan** [prophecymud/go-prophecy-issues#46]
Very minor, but the commands stat and max - the output for both is bleeding. 

Using JMC. Qethia saw it in her client also. 

![2019-11-30 13_40_45-Window](https://user-images.githubusercontent.com/30678526/69904665-173b0000-1377-11ea-9b73-ef3ba87b5059.png)

**Comment by Ranfir** [comment]
Also shows up in score.

**Comment by anhegofcherek** [comment]
Well-found, thanks!

This is an interesting one - here's the actual format string:

```
"-`#Str``: `^%d`*[`$%d`*] `#Int``: `^%d`*[`$%d`*] `#Wis``: `^%d`*[`$%d`*] `#Dex``: `^%d`*[`$%d`*] `#Con``: `^%d`*[`$%d`*]``\n\r"
```

Turns out I implemented colour parsing slightly differently in GoProph, so unknown colour codes (the `*`s in this case) did nothing, rather than acting as a reset.

I can fix these specific usages, but I'd be interested in your thoughts on the general behaviour - I think I slightly prefer the new GoProphecy behaviour here as it makes it more obvious when you've made a mistake, but I'm also conscious of the impact on existing strings...

**Comment by grekan** [comment]
I doubt this is all that common, although why `* was used at all is odd. My understanding is ROM didn't include colour stock and thus this must have been implemented at a later date. Possibly the imm who implemented colours didn't fully understand the parsing immediately? 

I always kind of wondered why there weren't 2 greys (`8 vs `*) like every other colour. Is it possible this was left out somehow?

I can't imagine it's all that common in areas.

**Comment by anhegofcherek** [comment]
I'd always assumed stats/maxstats were stock ROM, but apparently not!

> I always kind of wondered why there weren't 2 greys (8 vs *) like every other colour. Is it possible this was left out somehow?

Actually it's the `8` that's out of place!

https://en.wikipedia.org/wiki/ANSI_escape_code#3/4_bit

`1`-`7` correspond to 31-37 in that table, while `!`-`&` are 91-97 (the "bright" versions)

`8` is 90 there, "bright black" - arguably for consistency `*` should be "bright black" while `8` should be `30`, an explicit black (heck arguably `0` and `)` would be more consistent, and I'm tempted to add them...)

**Comment by anhegofcherek** [comment]
Fixed the usages - thanks!

```
 Fix colour code usage in stats/maxstats/score

Previously these used the * colour code, which wasn't a defined code.

In CProph, colour parsing would treat unknown codes as reset. When I
ported the parsing, I (intentionally or unintentionally) changed the
behaviour so that unknown codes just had no effect, thus causing colour
bleed, which made the usage of * stand out.

Discussion around the change in parsing behaviour has concluded that it
shouldn't be problematic - it's not unreasonable, and behaviour for
unknown codes wasn't especially well-defined, and we don't anticipate
there being many examples of it.

Thus I'm just fixing usages and leaving the new parser behaviour as-is
```
