### ISSUE TITLE
Timezone on GoProph is Central Eastern Time

### ISSUE THREAD

**Issue by grekan** [prophecymud/go-prophecy-issues#49]
C Proph Output of time:

It is 5 o'clock am, Day of the Sun, 20th the Month of the Dark Shades.
Prophecy started up at Sat Nov 30 10:00:21 2019

The system time is Sat Nov 30 19:57:05 2019
 UTC.

GoProph Output of Time:

It is 9 o'clock am, Day of Freedom, 44th the Month of Nature.
Prophecy started up at Sat Nov 30 14:54:37 CET 2019
The system time is Sat Nov 30 19:57:00 CET 2019.

Given everyone can reference off of UTC kind of weird that it's not a standard timezone like GMT or UTC.

**Comment by anhegofcherek** [comment]
Thanks, fixed
