### ISSUE TITLE
wimpy disabled

### ISSUE THREAD

**Issue by Ranfir** [prophecymud/go-prophecy-issues#54]
CProph lets me set wimpy, but GoProph gives "Wimpy is currently disabled for you."

**Comment by Ranfir** [comment]
I'm having trouble reproducing this one now. Unclear why.

**Comment by anhegofcherek** [comment]
You'll get that message if you're PK, in a quest, or in a scrim, if that helps...?

**Comment by Ranfir** [comment]
My recollection is that I was in an Emily FTI Quest.
