### ISSUE TITLE
"(originally the corpse of %s)"

### ISSUE THREAD

**Issue by Ranfir** [prophecymud/go-prophecy-issues#55]
You identify the corpse of The Demon Lord (originally the corpse of %s):

**Comment by anhegofcherek** [comment]
Nicely spotted, thanks

Unfortunate interaction between my show-original-strings functionality and how corpses work!

**Comment by anhegofcherek** [comment]
I've removed this functionality from corpse code because it's a little icky, so now the corpse base objects can be edited to something nicer - thanks :)
