### ISSUE TITLE
GoProph recognizes me as clanned, but not as Clan Leader.

### ISSUE THREAD

**Issue by Qethia** [prophecymud/go-prophecy-issues#8]
Ex.
[(   )] [Drasnian       ] [Sheps] [Shepherds] (New) [Wed]  Qethia, repatriated to - Prophecy -
(no clan title)

-You are a member of [Sheps] [Shepherds] 
(nothing stating I am clan lord of Sheps)

**Comment by anhegofcherek** [comment]
Thanks!

I think this is just a data issue - it's currently running with game data from a few years back (where you were leader of Spellbinders) but a recent character backup

I've just set you as leader of Shepherds - let me know if that hasn't fixed things please?
