### ISSUE TITLE
auction list indexing / formatting

### ISSUE THREAD

**Issue by Ranfir** [prophecymud/go-prophecy-issues#83]
Item #1 is indexed as 0. Also, the last two items aren't aligned with the first three items.
```
auc list
 #. Type    Minimum Bid        Item
*0. gold    10                 a city guard signet ring
*1. gold    10                 a standard issue sword
*2. gold    10                 a standard issue vest
*3. gold    100000              a war banner
*4. gold    1000000              (Quest) Aquest light
Item #1 is currently being auctioned, current bid is 0
NOTE: Item's with * are items you currently have up for auction.
```

The indexing issue arises specifically when there are multiple items on the list.

**Comment by anhegofcherek** [comment]
> Item #1 is indexed as 0

Now fixed, thanks!

> Also, the last two items aren't aligned with the first three items.

Prophecy issue, though alignment is generally nontrivial so I'm not sure how I feel about it...
