### ISSUE TITLE
aqeq limits

### ISSUE THREAD

**Issue by Ranfir** [prophecymud/go-prophecy-issues#85]
Unclear if this is specific to GoProph.

**You can enchant your aqeq beyond level 91.**
```
aq enchant cloak dex force
You add 2 dexterity to your (Quest) Aquest cloak, making it level 110 to use!
```

**You can enchant your aqeq stats beyond reasonable limits.**
```
You identify (Quest) Aquest cloak (originally (no short description)):

Object '-****- aquesteq cloak' is type armor.
Extra flags: no_locate burn_proof.
Weight is 1, value is 0, wear level is 115.
Object is owned by Hjma.
Wear location is torso.
Armor class is 30 pierce, 30 bash, 30 slash, and 30 vs. magic.
Affects dexterity by 12.
Affects armor class by -30.
Affects saves by -10.
Affects mana by 120.
Affects hp by 120.
```

**Comment by anhegofcherek** [comment]
> You can enchant your aqeq beyond level 91.

This is on CProph too - allowing people to make "trophy pieces"

**Comment by anhegofcherek** [comment]
> You can enchant your aqeq stats beyond reasonable limits.

That...doesn't look right, thanks!

**Comment by anhegofcherek** [comment]
(A lot of these aqeq changes finally went live as things were getting busy for me IRL though, so I under-documented things, so I'm going to go exploring and see...!)

**Comment by anhegofcherek** [comment]
Nicely found, thanks

**Comment by anhegofcherek** [comment]
Bug introduced when porting over the code that checks for objects going over limits - well spotted, thanks!

**Comment by anhegofcherek** [comment]
Should now be fixed
