### ISSUE TITLE
Emily Time Zones

### ISSUE THREAD

**Issue by grekan** [prophecymud/go-prophecy-issues#87]
Much like #49 Emily time is in CET. 

![image](https://user-images.githubusercontent.com/30678526/71702064-640d5e80-2d9b-11ea-9466-8b7bccd03250.png)

**Comment by anhegofcherek** [comment]
Thanks - turns out there were a tonne of places (pk, note, finger, punish, score, etc.!) I'd forgotten to convert times to UTC before displaying - should now be fixed!
