### ISSUE TITLE
Mud Actual Time Makes No Sense

### ISSUE THREAD

**Issue by grekan** [prophecymud/go-prophecy-issues#88]
I'm not sure what the months and days are in the mud, but I highly doubt a month has over 1000 days in it. 

Current time on Live:

![image](https://user-images.githubusercontent.com/30678526/71702110-9b7c0b00-2d9b-11ea-8020-a94b0596308a.png)

It's the 16th of the Month of Futility

Time on Go Proph:

![image](https://user-images.githubusercontent.com/30678526/71702123-a8006380-2d9b-11ea-992a-01fb1309ef4b.png)

It's somehow the 1313th of the Month of Nature. 

0 impact bug, but odd nonetheless.

**Comment by anhegofcherek** [comment]
Ugh this code is all a bit hacky - thanks for spotting it!

I should probably recruit some people to come up with a more Eddings-appropriate calendar...

**Comment by anhegofcherek** [comment]
Should now be fixed, thanks!

**Comment by grekan** [comment]
Just to add a note, as far as I can find there's no official months. Rivan Codex specifically mentions holidays but not months.

**Comment by anhegofcherek** [comment]
> Just to add a note, as far as I can find there's no official months. Rivan Codex specifically mentions holidays but not months.

Bah - thanks for looking!
