### ISSUE TITLE
Stash inaccessible

### ISSUE THREAD

**Issue by Ranfir** [prophecymud/go-prophecy-issues#89]
I can see it, but I can't retrieve anything from it.
```
exam stash
Your stash contains:
     a canoe
<snip>

[2891/2891 1917/1917 651/651 1000|   ] (6600|7700 0:00) (ESW) < > 
( )
get canoe stash
I see no stash here.
```

**Comment by Ranfir** [comment]
Seems to be the case on my KoP alts as well.

**Comment by anhegofcherek** [comment]
Fixed, thanks! Forgot it was actually live on CProph so I'd disabled it when porting - re-enabled now!
