### ISSUE TITLE
adding / removing items to/from containers in hostel causes lag

### ISSUE THREAD

**Issue by Ranfir** [prophecymud/go-prophecy-issues#92]
Might be that amount of lag is proportional to number if items in hostel or in bag.

**Comment by Ranfir** [comment]
Note that this definitely did not manifest during testing.

**Comment by anhegofcherek** [comment]
Thanks

This is almost certainly an IO issue - when you add/remove an item from a saveover room, the entire object list is written to disk, which unsurprisingly has the potential to be slow.

The box I was using for dev didn't have _good_ disks, but they seem better than the ones we have on the live box - I'll look into both sorting better disk and also making the code more performant, thanks!

**Comment by anhegofcherek** [comment]
This should be better now - I've improved the way objects are serialised

Have a go please and let me know how it feels?

**Comment by anhegofcherek** [comment]
I believe this should now be resolved - please let me know if not!
