### ISSUE TITLE
aq request apparently caused a crash

### ISSUE THREAD

**Issue by Ranfir** [prophecymud/go-prophecy-issues#98]
Crash occurred shortly before Sat Jan 11 06:22:17 UTC 2020.
Not the first auto quest I did, and I have no further clues. If I had to guess, some invalid random auto quest was generated that the game couldn't cope with?

**Comment by Ranfir** [comment]
Again shortly before Sat Jan 11 09:12:50 UTC 2020.

**Comment by anhegofcherek** [comment]
So it did, thank you - off-by-one error in the code that generates a random aquest giver.

Well-found, thanks!

**Comment by anhegofcherek** [comment]
Should now be fixed, will redeploy live shortly!
